In [1]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2,-3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [2]:
def load_array(data_arrays, batch_size, is_train=True): #@save
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [3]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[-1.2371502 ,  0.99518913],
        [ 0.12846069, -0.41475955],
        [-1.3619866 , -1.509596  ],
        [-0.302899  ,  0.591555  ],
        [-0.09313672,  0.05970319],
        [ 1.1874565 ,  1.5697803 ],
        [-1.0883249 , -0.77193904],
        [-0.7558182 ,  1.1483127 ],
        [ 1.104224  ,  1.9984574 ],
        [-1.4291492 ,  0.320298  ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[-1.6643847 ],
        [ 5.8524637 ],
        [ 6.62237   ],
        [ 1.577179  ],
        [ 3.8127222 ],
        [ 1.2514818 ],
        [ 4.654276  ],
        [-1.1983638 ],
        [-0.38890553],
        [ 0.24384072]], dtype=float32)>)

In [15]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1,kernel_initializer=initializer))

loss = tf.keras.losses.Huber()

In [7]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [16]:
num_epochs = 3
for epoch in range(num_epochs):
    for X,y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l=loss(net(features), labels)
    print(f'epoch {epoch+1}, loss{l:f}')

epoch 1, loss2.218774
epoch 2, loss0.476817
epoch 3, loss0.002318


In [17]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([ 0.02782953 -0.0465219 ], shape=(2,), dtype=float32)
error in estimating b [0.04267073]
